### ISSUE TITLE
I tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcupti.so. 

### ISSUE THREAD

**Issue by SeekPoint** [MehdiAB161/Autoencoder-Stability#4]
rzai@rzai00:~/prj/Neural-Networks-for-Collaborative-Filtering$ CUDA_VISIBLE_DEVICES=1 python3 main.py
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
/usr/local/lib/python3.4/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
.................................................................................................
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /home/rzai/prj/Neural-Networks-for-Collaborative-Filtering/autoencoder/Autoencoder.py:76 in run_training.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.43GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
I tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcupti.so. LD_LIBRARY_PATH: /home/rzai/torch/install/lib:/home/rzai/torch/install/lib:/home/rzai/torch/install/lib:/home/rzai/torch/install/lib:/usr/local/cuda-8.0/lib64:/home/rzai/torch/install/lib:/home/rzai/torch/install/lib:/home/rzai/torch/install/lib:/home/rzai/torch/install/lib:
F tensorflow/core/platform/default/gpu/cupti_wrapper.cc:59] Check failed: ::tensorflow::Status::OK() == (::tensorflow::Env::Default()->GetSymbolFromLibrary( GetDsoHandle(), kName, &f)) (OK vs. Not found: /usr/local/lib/python3.4/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cuptiActivityRegisterCallbacks)could not find cuptiActivityRegisterCallbacksin libcupti DSO

Aborted (core dumped)
rzai@rzai00:~/prj/Neural-Networks-for-Collaborative-Filtering$

**Comment by MehdiAbbanaBennani** [comment]
It seems like libcupti.so might be missing from your CUDA library, you can try installing cupti library using the following command:
`sudo apt-get install libcupti-dev`

**Comment by SeekPoint** [comment]
fixed
