### ISSUE TITLE
TypeError: listdir() missing 1 required positional argument: 'path'

### ISSUE THREAD

**Issue by SeekPoint** [MehdiAB161/Autoencoder-Stability#6]
Train Data Eval:
0.5560789520477667
differences evaluation time 15.92467975616455
check self.rmse different from zero:
0.5560789520477667
check that the value changed
check assertion
WARNING:tensorflow:From /home/rzai/prj/Neural-Networks-for-Collaborative-Filtering/stability/AutoencoderStability.py:81 in run_training.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
epoch 14.0
Test Data Eval:

--- parameters ---
{'stability': {'probability': 0.80000000000000004, 'subsets_number': 3, 'rmse': 0.5560789520477667, 'first_learning': 'autoencoder', 'landa_array': array([ 0.42600274,  0.3418732 ,  0.1191205 ,  0.11300356]), 'differences': <3952x6040 sparse matrix of type '<class 'numpy.float32'>'
	with 900188 stored elements in Compressed Sparse Row format>}, 'rmse': {'autoencoder': 0.8819002411444694, 'stability_factorisation': 0.984447690186304, 'stability_autoencoder': 0.983267223202749}, 'factorisation': {'iterations': 10, 'dimension': 10, 'landa': 3}, 'autoencoder': {'learning_decay': 0.90000000000000002, 'regularisation': 0.20000000000000001, 'learning_rate0': 0.001, 'hidden1_units': 700, 'batch_size_evaluate': 100, 'is_test': True, 'batch_size_train': 35, 'nb_epoch': 15}, 'experiments': {'mean_iterations': 1, 'nb_draws': 30}, 'sets': {'validation_ratio': 0.10000000000000001, 'database_id': 1, 'learning_type': 'V', 'test_ratio': 0.10000000000000001}}
--- rmse ---
0.9854376045587415
--- 202.1434624195099 seconds ---
----------------------------------------

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from config.stability.V_1M import Experiment
  File "/home/rzai/prj/Neural-Networks-for-Collaborative-Filtering/config/stability/V_1M.py", line 50, in <module>
    Experiment.run()
  File "/home/rzai/prj/Neural-Networks-for-Collaborative-Filtering/autoencoder/Experiment.py", line 127, in run
    self.log_to_file()
  File "/home/rzai/prj/Neural-Networks-for-Collaborative-Filtering/autoencoder/Experiment.py", line 42, in log_to_file
    file_name = log_folder() + 'log.txt'
  File "/home/rzai/prj/Neural-Networks-for-Collaborative-Filtering/tools/tools.py", line 64, in log_folder
    test_n = len(list(n for n in folder.listdir() if n.startswith('test')))
TypeError: listdir() missing 1 required positional argument: 'path'
rzai@rzai00:~/prj/Neural-Networks-for-Collaborative-Filtering$

**Comment by MehdiAbbanaBennani** [comment]
I'm sorry I'm quite busy these days, I will look into the matter as soon as I can.
However, you shouldn't worry about this error, there is some bug in logging the results into a file.

**Comment by HalfClock** [comment]
I also encountered this problem. The listdir function seems to require a parameter like a path string. However, the folder already contains the required path parameters. So, I added a null character in the listdir function, like this "folder.listdir('')" and I have solved this prorblem
